name = 'hosuto'
main = 'src/app.ts'
compatibility_date = '2024-12-24'
minify = true

[[kv_namespaces]]
binding = 'KV'
id = '<KV NAMESPACE ID>'

[vars]
CLOUDFLARE_EMAIL = '<CLOUDFLARE ACCOUNT EMAIL>'
CLOUDFLARE_API_KEY = '<CLOUDFLARE API KEY>'
CLOUDFLARE_ACCOUNT_ID = '<CLOUDFLARE ACCOUNT ID>'